# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.poommie }}

    strategy:
      matrix:
        poommie: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  docker:
      needs: build
      runs-on: ubuntu-latest # Docker is typically installed by default on Ubuntu runners.
      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io
              if: runner.os == 'Linux'

              - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/<image_name>:latest
